### ISSUE TITLE
Warning: Unknown props `currentUser`, `ready`, `count`, `hasMore`, `loadMore` on <div> tag.

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [meteor-utilities/react-list-container#14]
This happens when the results get passed into a child comp of another library that uses the ...props when it likely should not. Not really an issue with this lib however, I think it would be useful enhancement to be able to fully specify what get's passed to the child comp. I will code up a solution and create a PR in the next few days.

**Comment by SachaG** [comment]
I'm not really maintaining this package anymore, but if you'd like I'd be happy to give you control over it?

**Comment by MichaelLeeHobbs** [comment]
Are you using something better than this in place of it? If not then that's fine. This packages solves an issue for me.

**Comment by SachaG** [comment]
I've switched to Apollo so I basically wrote an Apollo version of this package.
