### ISSUE TITLE
Unsubscribe on componentWillUnMount ?

### ISSUE THREAD

**Issue by yched** [meteor-utilities/react-list-container#2]
If the component subscribes to a publication, then shouldn't it also unsubscribe when it unmounts ?

**Comment by SachaG** [comment]
I think that's handled for you automatically? I could be wrong though.

**Comment by yched** [comment]
Not to my knowledge :-)

**Comment by SachaG** [comment]
Maybe I'm wrong but this seems to imply it does stop automatically? 

https://github.com/kadirahq/react-komposer/issues/5#issuecomment-172115989

**Comment by yched** [comment]
Hm, that's probably the case, yeah.

The getMeteorData mixin stops the reactive computation on componentWillUnmount. IIRC, Tracker takes care of stopping the subscriptions made within an autorun when that autorun is stopped, right ?

**Comment by yched** [comment]
Finally got a chance to double check this, and yes tracker does unsubscribe automatically for us.

Sorry for the noise :-)
